name             'winservice'
maintainer       'Amitraj Budhu'
maintainer_email 'abudhu@gmail.com'
license          'All rights reserved'
description      'Installs/Configures winservice'
long_description 'Installs/Configures winservice'
version          '0.1.0'
